---
title: "Concusion and Future Implications"
---

### Summary
The research hypothesis in question pertained to chronic absenteeism by race/ethnicity being affected by the geographic region in the U.S.  Results indicate that the West region significantly predicted chronic absenteeism in American Indian/Alaska Native, Native Hawaiians/other Pacific Islander, and white students; the South significantly predicted chronic absenteeism in Asian and Hispanic/Latino of any race students.  The following had a significantly higher proportion of students with  chronic absenteeism in another region compared to the Northeast region: American Indian/Alaska Native, Native Hawaiian/Pacific Islander, whites; while the follwoing groups had a lower percentage of chronic absenteeism in another region compared to the Northeast: Asian and Hispanic/Latino.  This may make sense in particular situations, such as the American Indian/Alaska Native proportion being higher in the West than in the Northeast (i.e., since this ethnicity group originated in the West, these people may tend to be more rooted in their culture than those who move to another region such as the Northeast, which may cause a higher proportion of chronic absenteeism due to cultural reasons/practices).

### Conclusion and Future Implications
One surprising piece of information suggested from these analyses is that chronic absenteeism of blacks/African American students, students of two or more races, and chronic absenteeism by all races/ethnicities combined were not significantly affected by geographic region.  However, other variables such as SES, type of school district setting (i.e., urban versus suburban), parental demographics (education level, marital status, legal history, employment, etc.), and housing history (i.e. foster care system) may explain more of this variance.  These, among other variables, may also be underlying constructs as to why these geographic regions made an impact on the races/ethnicities that they did.  A limitation of this study is that this underlying information that may be inherent to more extensive analyses was not available through these data sets.  This leads to the call for further study to examine the nature of the relationships of how race, geographic region, and other variables are related to chronic absenteeism in the U.S., and how we may build on this information to find useful and efficient solutions for chronic absenteeism and work towards closing achievement gaps.